- name: create user_lists
  set_fact:
    user_vars: "{{ item.username }}" #user_varsにユーザ名を格納
  loop: "{{ user_group_lists }}"

- name: Check if wp-config exists #whenの判定で使用
  stat:
    path: /var/www/dev.menta.me/wp-config.php
  register: wordpress_wp_config #-を使用するとエラーが起きたので_を使用

- name: Download latest Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /var/www/dev.menta.me/wordpress.tar.gz
  when: not wordpress_wp_config.stat.exists

- name: Extract wordpress
  unarchive:
    src: /var/www/dev.menta.me/wordpress.tar.gz
    dest: /var/www/dev.menta.me/
    remote_src: yes
    extra_opts: ["--strip-components=1"]
  when: not wordpress_wp_config.stat.exists

- name: remove file
  shell: |
    rm -f /var/www/dev.menta.me/wp-config-sample.php
    rm -f /var/www/dev.menta.me/wordpress.tar.gz
  when: not wordpress_wp_config.stat.exists

- name: copy wp-config.php
  template:
    src: "roles/wordpress/files/wp-config.php"
    dest: /var/www/dev.menta.me/
  when: not wordpress_wp_config.stat.exists

- name: Set permissions for Wordpress
  file:
    path: /var/www/dev.menta.me
    owner: nginx
    group: nginx
    recurse: yes
    state: directory
