- name: install remi epel
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ PHP_VERSION_EPEL }}"
    - "{{ PHP_VERSION_REMI }}"

- name: Set priority for Remi PHP 7.4 repository
  ini_file:
    path: /etc/yum.repos.d/remi-php74.repo
    section: remi-php74
    option: priority
    value: "1"

- name: php74 install
  yum:
    name: "{{ item }}"
    enablerepo: remi,remi-php74
    state: present
  loop:
    - php
    - php-fpm
    - php-gd
    - php-mbstring
    - php-xml
    - php-curl
    - php-mysqlnd
    - php-pdo
    - php-bcmath
    - php-ldap

- name: start php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: copy php-fpm www.conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
    mode: "0664"
  loop:
    - { src: "www.conf", dest: /php-fpm.d/ }
    - { src: "php.ini", dest: . }
  notify: restart php-fpm
