- name: Ensure /etc/nginx/conf.d directory exists
  file:
    path: /var/www/dev.menta.me
    state: directory
    mode: "0755"

- name: copy nginx.repo
  copy:
    src: roles/nginx/files/nginx.repo
    dest: /etc/yum.repos.d/.

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: copy nginx conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
  loop:
    - { src: roles/nginx/files/conf.d, dest: . }
    - { src: roles/nginx/files/nginx.conf, dest: . }

- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
  notify: restart nginx
